events {}

http {
    upstream users { server user-service:5000; }
    upstream products { server product-service:5000; }
    upstream cart { server cart-service:5000; }
    upstream orders { server order-service:5000; }

    server {
        listen 80;

        location /api/users/ {
            proxy_pass http://users/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/products/ {
            proxy_pass http://products/;
            proxy_set_header Host $host;
        }

        location /api/cart/ {
            proxy_pass http://cart/;
            proxy_set_header Host $host;
        }

        location /api/orders/ {
            proxy_pass http://orders/;
            proxy_set_header Host $host;
        }

        location /health {
            return 200 '{"status":"gateway healthy"}';
            add_header Content-Type application/json;
        }

        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }
    }
}
